/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicFolderRouteImport } from './routes/api/public/folder'
import { Route as ApiPublicStreamRouteImport } from './routes/api/public/stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFolderRoute = ApiPublicFolderRouteImport.update({
  id: '/api/public/folder',
  path: '/api/public/folder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStreamRoute = ApiPublicStreamRouteImport.update({
  id: '/api/public/stream',
  path: '/api/public/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/folder': typeof ApiPublicFolderRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/folder': typeof ApiPublicFolderRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/folder': typeof ApiPublicFolderRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/folder' | '/api/public/stream'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/folder' | '/api/public/stream'
  id: '__root__' | '/' | '/api/public/folder' | '/api/public/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicFolderRoute: typeof ApiPublicFolderRoute
  ApiPublicStreamRoute: typeof ApiPublicStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/folder': {
      id: '/api/public/folder'
      path: '/api/public/folder'
      fullPath: '/api/public/folder'
      preLoaderRoute: typeof ApiPublicFolderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stream': {
      id: '/api/public/stream'
      path: '/api/public/stream'
      fullPath: '/api/public/stream'
      preLoaderRoute: typeof ApiPublicStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicFolderRoute: ApiPublicFolderRoute,
  ApiPublicStreamRoute: ApiPublicStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
